[%
    T = {
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        viewjs_1                                   = "IntranetUserJS: Replace patron info in Transfers to receive -report to a checkmark",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Replace patron info in Transfers to receive -report to a checkmark &rsaquo; View JS plugin",
    }
%]
