[%
    T = {
        configure_1                                = "IntranetUserJS: Replace patron info with a checkmark in Transfers to receive report > Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Replace patron info with a checkmark in Transfers to receive report &rsaquo; Configuration",
        configure_5                                = "Report ID to be used:",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Replace patron info with a checkmark in Transfers to receive report",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Replace patron info with a checkmark in Transfers to receive report &rsaquo; View JS plugin",
    }
%]
