[%
    T = {
        configure_1                                = "IntranetUserJS: Transfers to receive patron info to checkmark Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Transfers to receive patron info to checkmark &rsaquo; Configuration",
        configure_5                                = "Report ID to be used:",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Transfers to receive patron info to checkmark",
        viewjs_2                                   = "&rsaquo; TransferstoreceivePatronInfoCheckmark &rsaquo; View JS Tool",
    }
%]
