[%
    T = {
        configure_1                                = "IntranetUserJS: Korvaa asiakastiedot oikein-merkillä Vastaantotettava kuljetukset -raportilla Asetukset",
        configure_2                                = "Koti",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Korvaa asiakastiedot oikein-merkillä Vastaantotettava kuljetukset -raportilla &rsaquo; Asetukset",
        configure_5                                = "Käytettävän raportin ID:",
        configure_6                                = "Tallenna konfiguraatio",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Korvaa asiakastiedot oikein-merkillä Vastaantotettava kuljetukset -raportilla",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Korvaa asiakastiedot oikein-merkillä Vastaantotettava kuljetukset -raportilla &rsaquo; Näytä JS-liitännäinen",
    }
%]
