[%
    T = {
        configure_1                                = "IntranetUserJS: Siirrot vastaanottavat asiakastiedot valintamerkkiä varten - Asetukset",
        configure_2                                = "Koti",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: siirrot vastaanottavat asiakastiedot valintamerkkiä varten &rsaquo; Asetukset",
        configure_5                                = "Käytettävän raportin ID:",
        configure_6                                = "Tallenna konfiguraatio",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Siirrot vastaanottavat asiakastiedot valintamerkkiä varten",
        viewjs_2                                   = "&rsaquo; TransferstoreceivePatronInfoCheckmark &rsaquo; Näytä JS-Työkalu",
    }
%]
