[%
    T = {
        configure_2                                = "Koti",
        configure_3                                = "Liitännäiset",
        viewjs_1                                   = "IntranetUserJS: Korvaa Vastaanotettavat kuljetukset -raportilla asiakkaan tiedot oikein-merkillä",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Korvaa Vastaanotettavat kuljetukset -raportilla asiakkaan tiedot oikein-merkillä &rsaquo; Näytä JS-liitännäinen",
    }
%]
