[%
    T = {
        configure_1                                = "IntranetUserJS: Transporter för att ta emot låntagarinformation till bockmarkering Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Moduler",
        configure_4                                = "&rsaquo; IntranetUserJS: Transporter för att ta emot låntagarinformation till bockmarkering &rsaquo; Konfiguration",
        configure_5                                = "ID för rapporten som ska användas:",
        configure_6                                = "Spara konfiguration",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Insticksmodulen har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Transporter för att ta emot låntagarinformation till bockmarkering",
        viewjs_2                                   = "&rsaquo; TransferstoreceivePatronInfoCheckmark &rsaquo; Visa JS-verktyg",
    }
%]
