[%
    T = {
        configure_1                                = "IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten > Inställningar",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten &rsaquo; Inställningar",
        configure_5                                = "ID för rapporten som ska användas:",
        configure_6                                = "Spara konfiguration",
        configure_7                                = "Uppdateringsstatus",
        configure_8                                = "Plugin har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten &rsaquo; Visa JS-plugin",
    }
%]
