[%
    T = {
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        viewjs_1                                   = "IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Ersätter låntagarinformation med bockmarkering i Överföringar att ta emot-rapporten &rsaquo; Visa JS-plugin",
    }
%]
